### ISSUE TITLE
error when removing IP from Route53

### ISSUE THREAD

**Issue by jbmcgill** [tegioz/lbManager#1]
Hi, I'm getting an error when removing an IP from a Route 53 configuration:

Setting the IP works and I can confirm that it is setup in the AWS Route 53 Console

```
> /usr/bin/etcdctl set /lbManager/route53/us-west-2/Z1P4WHKKYJ6YMV/fiber.red/single/10.74.129.185 ""
> fleetctl journal fiber-lbmanager
Jul 07 04:51:43 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: ->      ROUTE53:fiber.red:setSingleMember:10.74.129.185
Jul 07 04:51:43 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: --   ROUTE53:fiber.red:syncing:[10.74.129.185]
Jul 07 04:51:43 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: -- ZONEUPDATER:Z1P4WHKKYJ6YMV:updating:fiber.red:[10.74.129.185]
```

But removing the IP doesn't work and I can confirm that the entry is not removed in the AWS Route 53 Console:

```
> /usr/bin/etcdctl rm /lbManager/route53/us-west-2/Z1P4WHKKYJ6YMV/fiber.red/single/10.74.129.185 
>  fleetctl journal fiber-lbmanager
Jul 07 04:52:07 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: <- ROUTE53:fiber.red:removeMember:10.74.129.185
Jul 07 04:52:07 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: -- ROUTE53:fiber.red:syncing:[]
Jul 07 04:52:07 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: -- ZONEUPDATER:Z1P4WHKKYJ6YMV:updating:fiber.red:[]
Jul 07 04:52:07 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: Request failed, got status code: 400. Response: <?xml version="1.0"?>
Jul 07 04:52:07 ip-10-74-129-171.us-west-2.compute.internal docker[19682]: <ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>eb9aa185-2463-11e5-85be-4d898eb51618</RequestId></ErrorResponse>
```

Any pointers greatly appreciated!

**Comment by jbmcgill** [comment]
Looks like it might be an issue with an old container on quay.io, I see that container is 10 months old so I guess it wouldn't have the newer commits. The container at misakai/lbmanager on the docker hub seems to work. Closing issue.

**Comment by tegioz** [comment]
Hi @jbmcgill,

Sorry about the late response. 

You are right, the image available on quay.io is a bit outdated. I haven't pushed it again since the first commit, so it doesn't include some later fixes. I'll build and push it again as soon as possible, thanks for letting me know.

Just in case you want to build your own image, you'll find the Dockerfile used to build the current one in the docker folder of the project, it should work fine.
